version: "3.1"
services:
  springbootapp:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: springbootapp
    network_mode: bridge
    expose:
      - 8080
    ports:
      - 8080:8080
    env_file:
      - .env
#    depends_on:
#      - postgres
#    links:
#      - postgres