version: '3.1'
services:
  app:
    container_name: springbootdemo
    image: springbootdemo
    build: ./
    ports:
      - "8080:8080"

#  postgres:
#    image: postgres:latest
#    container_name: postgres
#    network_mode: bridge
#    expose:
#      - 5432
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_PASSWORD: admin
#      - POSTGRES_USER = postgres
#      - POSTGRES_DB = testdb